src/app/app.module.ts
src/app/components/header/header.component.html
src/app/components/header/header.component.ts

Fix Dropedown menu header

---

src/app/components/about/about.component.html
src/app/components/home/home.component.html
src/app/components/home/home.component.ts
src/app/components/portal-statistics/portal-statistics.component.html
tailwind.config.js

Update about and home components

---

src/app/components/filter/filter.component.ts
src/app/components/search-results/search-results.component.html

Fix fetching of filter values + div centering issue

Fix fetching of filter values + div centering issue

---

src/app/about/page.tsx

created the about page for GDI:
- the about page contain links to issue trackers
- the about page contain links to existing documentation
- the about page discribes User Portal and GDI
- the new feature responsive

feat: #59 Develop About page

---

src/components/header.tsx

- fixed a bug where the menu doesn't disappear when you click on an action
- fixed a bug where the menu doesn't disappear when you click anywhere on the screen
- fixed a bug where for certain screen sizes the menu doesn't appear 
https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/73106409/e4d0c096-a9ca-4aa4-b19e-509cfb4ea167

fix: #95 The actions menu dropdown does not close

---

src/app/about/page.tsx
src/components/header.tsx

I've noticed that 3 new colors have been added into our GDI app which are not present in our design guidelines. While these changes may enhance visual appeal but i believe adhering to color palette is quite important for brand consistency, visual harmony and professionalism.
If we don't actively look out for this, we could end up with a lot of colours everywhere
I'm open to discuss and debate about this

feat: consistent colouring

---

src/app/about/page.tsx
src/app/datasets/[id]/DistributionAccordion.tsx
src/app/datasets/[id]/Sidebar.tsx
src/components/Chips.tsx
src/components/PageHeading.tsx
src/components/PageSubHeading.tsx

feat: Dataset details coloring

---

src/app/datasets/[id]/DistributionAccordion.tsx
src/app/datasets/[id]/Sidebar.tsx
src/app/error.tsx
src/components/PageHeading.tsx
src/components/PageSubHeading.tsx
src/components/button.tsx
src/components/footer.tsx
src/components/header.tsx
tailwind.config.js

I made a mistake in naming.
Actually we have 2 purple colors: light one and dark one
We have been using light purple everywhere as primary color but i named it secondary
So light purple should be called primary

fix: primary is secondary and vice-versa

---

src/components/DatasetCounter.tsx
src/services/ckan/__tests__/datasetCount.test.ts
src/services/ckan/datasetCount.ts
src/services/ckan/index.server.ts

- Implement datasetCount.ts service to fetch data from backend
- Implement DatasetCounter/tsx component

feat: #57 Implement dataset counter

---

src/app/layout.tsx
src/components/button.tsx
src/components/datasetItem.tsx
src/components/datasetList.tsx
src/providers/DatasetBasketProvider.tsx

feat: Add to basket button, And DatasetBasketProvider

---

src/app/basket/page.tsx
src/components/button.tsx
src/components/datasetItem.tsx
src/components/datasetList.tsx
src/components/header.tsx
src/providers/DatasetBasketProvider.tsx

feat: Basket list page

---

src/components/header.tsx

feat: Only show icon with number

---

src/app/datasets/[id]/AddToBasketBtn.tsx
src/app/datasets/[id]/page.tsx
src/components/header.tsx

feat: Add to Basket button on dataset details page

---

src/components/Alert.tsx

feat: Alert Box

---

src/components/avatar.tsx
src/components/header.tsx
src/components/notification.tsx

fix: use correct colors

---

src/app/applications/[id]/page.tsx
src/app/layout.tsx
src/components/fieldAttachmentContainer.tsx
src/components/fileUploaded.tsx

feat: responsiveness for application details page

---

src/app/about/page.tsx
src/app/applications/[id]/page.tsx
src/app/applications/applicationItem.tsx
src/app/applications/page.tsx
src/app/basket/page.tsx
src/app/page.tsx
src/components/CenteredListContainer.tsx
src/components/List/ListItem.tsx
src/components/List/index.tsx
src/components/PageContainer.tsx
src/components/datasetItem.tsx
src/components/datasetList.tsx

This PR deals with refactoring and extracting out common logic into sharable components to avoid duplicacy and inconsistency across the app

feat: PageContainer, CenteredListContainer, List, ListItem common components

---

src/app/applications/ApplicationItem.tsx

feat: Link Application Details page in the list view

---

src/app/applications/ApplicationItem.tsx
src/app/datasets/[id]/DistributionAccordion.tsx

Solved the text selection by adding animation

fix: unnecessary text selection during expansion

---

src/app/datasets/clientWrapper.tsx

The spacing is now consistent with all other pages on application. Also changed the filter icon to align with other places i.e. secondary buttons in info color background

fix: spacing and filter icon

---

src/app/datasets/FilterList/index.tsx
src/app/datasets/clientWrapper.tsx
src/components/Chips.tsx
src/components/button.tsx
src/components/datasetItem.tsx

fix: FilterList button colors, height and dataset item colors and chip colors

---

src/app/applications/page.tsx

https://catalog-test.healthdata.nl/applications is crashing but error page is not displayed

fix: Applications page error handling

---

src/app/basket/page.tsx
src/services/daam/client/createApplication.ts
src/types/application.types.ts

Backend PR
https://github.com/GenomicDataInfrastructure/gdi-userportal-access-management-service/pull/48

feat: Redirect to application page on success

---

src/app/datasets/[id]/AddToBasketBtn.tsx
src/app/datasets/[id]/DistributionAccordion.tsx
src/app/datasets/[id]/page.tsx

1) Fix spacing and responsiveness
2) File format is optional

fix: Dataset details page improvements

---

src/app/about/page.tsx
src/app/datasets/[id]/DistributionAccordion.tsx
src/app/datasets/[id]/page.tsx
src/components/PageContainer.tsx

fix: Longggg title and container spacing

---

src/components/datasetItem.tsx
src/services/discovery/types/dataset.types.ts

it looks like description is optional because im getting null with our current data

fix: Description can be optional

---

src/app/datasets/[id]/DistributionAccordion.tsx
src/app/datasets/[id]/page.tsx
src/app/datasets/[id]/sidebarItems.ts
src/components/datasetItem.tsx

- rename Publisher Name to Publisher;
- display themes, keywords and formats labels;

chore: improve UI value labels

---

.env.local.example
next.config.mjs
src/app/layout.tsx
src/app/page.tsx

this is a fix for the browser as it is blocking eval in script-src for scp.

fix: #191 blocked eval scr issue

---

src/app/Footer.tsx
src/app/datasets/page.tsx

https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/73106409/ef2494a1-76b5-4671-a781-56028bb8139b

fix: #188 update loading message for datasets search

---

src/components/Button.tsx

If the buttons disabled, no event can be assigned to it

Fix for disabling buttons

---

src/app/applications/[id]/page.tsx

feat: put back margin

---

src/app/applications/[id]/FieldContainer.tsx
src/app/applications/[id]/FormContainer.tsx
src/app/applications/[id]/page.tsx
src/components/Chip.tsx
src/components/Chips.tsx

fix: Application Layout spacing

---

src/app/applications/[id]/page.tsx
src/components/Alert.tsx
src/providers/application/ApplicationProvider.tsx

I noticed that application submission on my local fails with no error. So thought to show it.
I guess @emilianapali is working on similar thing for other pages?

fix: Show error if application submission fails

---

src/app/datasets/[id]/ClientSidebar.tsx
src/app/datasets/[id]/page.tsx

We are now getting the user time zone to format the date. Consequently, components using these formatted dates have to be client components. That was what caused the issue for the dataset details page.

fix: make sidebar client component

---

src/app/api/applications/[id]/__tests__/submit.route.test.ts
src/app/api/applications/[id]/submit/route.ts

Error formatting is already happening in the backend so no need to do it in the frontend

Remove formatting for ErrorMessages

---

.github/workflows/weekly_vuln_scan.yml

Vulnerability Scan Weekly - Licenses

---

src/app/applications/[id]/FieldContainer.tsx
src/app/applications/[id]/FileUploadFormField.tsx
src/app/applications/[id]/InputFormField.tsx
src/app/applications/[id]/TextAreaFormField.tsx
src/providers/application/ApplicationProvider.tsx
src/providers/application/ApplicationProvider.types.ts
src/types/application.types.ts
src/utils/__tests__/application.test.ts
src/utils/application.ts

253 gdi frontend support text typed fields

---

src/app/DatasetCounter.tsx
src/app/PortalStatistics.tsx
src/app/api/applications/[id]/__tests__/submit.route.test.ts
src/app/api/datasets/__tests__/route.test.ts
src/app/api/datasets/route.ts
src/app/api/errorHandling.ts
src/app/basket/page.tsx
src/app/datasets/[id]/page.tsx
src/app/error.tsx
src/app/layout.tsx
src/app/requests/applications/index.tsx
src/app/requests/entitlements/index.tsx
src/components/Alert.tsx
src/components/PageContainer.tsx
src/components/Searchbar.tsx
src/providers/AlertProvider.tsx
src/providers/application/ApplicationProvider.tsx
src/utils/ErrorResponse.ts

feat: Unified Error handling

---

src/app/requests/entitlements/EntitlementCard.tsx
src/app/requests/entitlements/EntitlementsList.tsx
src/app/requests/entitlements/index.tsx
src/components/DatasetCard.tsx
src/components/DatasetList.tsx

the feature is to decommission changes in dataset card related to entitlements, tried a couple of designs but at the end I kept the previous one, here is the implementation 
and here is the alternative:

264 gdi frontend design and develop entitlement card

---

src/app/Footer.tsx

1- add howto: it will be shown only if variable is defined in env.
2- organize footer content in tabular view. For now, only dataset has a proper link.

feat: restructure footer

---

package-lock.json

Reverts GenomicDataInfrastructure/gdi-userportal-frontend#425

Revert "chore(deps): bump micromatch from 4.0.5 to 4.0.8"
